modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "${issue_url}"
license = "${license}"

[[mods]]
modId = "no_render"
version = "${version}"
displayName = "${display_name}"
displayURL = "${homepage}"
authors = "${authors}"
description = "${description}"
logoFile = "icon.png"
displayTest="IGNORE_ALL_VERSION"

[[dependencies.no_render]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.no_render]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "no_render.mixins.json"

[[mixins]]
config = "no_render-common.mixins.json"
